name: Unit Tests (Coverage)

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db_test:
        image: postgres
        env:
          POSTGRES_USER: tests
          POSTGRES_PASSWORD: tests
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: "14.x"

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn install

      - name: run prisma migrate
        run: npx dotenv -e .env.test npx prisma migrate dev --name init

      - name: Collect coverage
        run: npx dotenv -e .env.test jest --ci --runInBand --no-cache --coverage --outputFile test-results.json --json
        env:
          CI: true
  
      - name: Danger CI
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}